#!/bin/bash

docker run \
  --rm \
  --name sidekiq \
  -w /app \
  -v $(pwd):/app \
  -v labs-gems:/usr/local/bundle \
  --network rebase-labs-network \
  -e REDIS_URL=redis://redis:6379/0 \
  -d \
  ruby \
  bash -c "bundle && bundle exec sidekiq -r ./worker.rb"
