#!/bin/bash

docker run \
  --rm \
  --name server-1 \
  -w /app \
  -v $(pwd):/app \
  -v labs-gems:/usr/local/bundle \
  -p 3000:3000 \
  --network rebase-labs-network \
  ruby \
  bash -c "bundle install && ruby server-1.rb"
